[package]
name = "ch11_automated_tests"
version = "0.1.0"
authors = ["Adeshina Ogunmodede <abdulwahabogunmodede@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
